export type WorkPermitCountry = {
  slug: string;
  country: string;
  code: string;
  region: string;
  image: string;
  href: string;
  permitTypes: string[];
  advisoryFocus: string;
  processingSignal: string;
  proofPoints: string[];
  routeReadiness: Array<{
    label: string;
    value: string;
    detail: string;
  }>;
  documentChecklist: string[];
  advisorChecks: string[];
};

export const workPermitCountries: WorkPermitCountry[] = [
  {
    slug: "canada",
    country: "Canada",
    code: "CA",
    region: "North America",
    image: "/images/skilled/canada/global-talent-stream.webp",
    href: "/skilled/canada/global-talent-stream",
    permitTypes: ["Global Talent Stream", "Employer-specific work permit", "LMIA-backed pathway", "Intra-company transfer"],
    advisoryFocus: "Employer support, NOC fit, wage evidence, LMIA/LMIA-exempt logic, and family work/study planning.",
    processingSignal: "High demand for technology, healthcare, trades, and employer-sponsored profiles.",
    proofPoints: ["Resume and role match", "Employer documentation", "Education and experience proof"],
    routeReadiness: [
      { label: "Sponsor basis", value: "Employer-led", detail: "Most routes need a Canadian employer or LMIA-exempt category." },
      { label: "Profile fit", value: "NOC + wage", detail: "Role duties, wage level, and experience must align." },
      { label: "Family planning", value: "Often possible", detail: "Spouse/dependent options depend on job category and status." },
    ],
    documentChecklist: ["Resume/CV", "Passport", "Education proof", "Employment letters", "Offer letter or employer details", "Language or licensing proof if applicable"],
    advisorChecks: ["NOC match", "LMIA vs LMIA-exempt pathway", "Employer compliance readiness", "Family permit strategy"],
  },
  {
    slug: "usa",
    country: "United States",
    code: "US",
    region: "North America",
    image: "/images/skilled/usa/h1b-visa.webp",
    href: "/skilled/usa/h1b-specialty-occupation",
    permitTypes: ["H-1B", "L-1 transfer", "O-1 profile review", "J-1 exchange visitor"],
    advisoryFocus: "Specialty occupation fit, employer sponsorship, profile strength, petition category, and evidence gaps.",
    processingSignal: "Best for sponsored roles, intra-company transfers, founders, researchers, and high-skill specialists.",
    proofPoints: ["Degree and role alignment", "Employer sponsorship", "Achievements or specialized skills"],
    routeReadiness: [
      { label: "Sponsor basis", value: "Required", detail: "H-1B/L-1/J-1 routes require a sponsor or qualifying host structure." },
      { label: "Profile fit", value: "Evidence-heavy", detail: "Degree, specialty role, prior employment, or exceptional profile must be documented." },
      { label: "Timing risk", value: "Category-led", detail: "Lottery, petition timing, premium processing, and consular slots vary by route." },
    ],
    documentChecklist: ["Resume/CV", "Passport", "Degree and transcripts", "Employment letters", "Job offer or petition basis", "Awards/publications if O-1/NIW direction"],
    advisorChecks: ["Specialty occupation fit", "L-1 qualifying relationship", "O-1 evidence strength", "Petition and consular readiness"],
  },
  {
    slug: "united-kingdom",
    country: "United Kingdom",
    code: "GB",
    region: "Europe",
    image: "/images/skilled/united-kingdom/uk-skilled-visa.webp",
    href: "/skilled/united-kingdom/uk-global-talent-visa",
    permitTypes: ["Skilled Worker", "Global Talent", "Expansion Worker", "Self-sponsorship direction"],
    advisoryFocus: "Sponsor readiness, occupation code, salary threshold, endorsement route, and dependent planning.",
    processingSignal: "Useful for sponsored employment, corporate expansion, founders, and exceptional talent profiles.",
    proofPoints: ["Certificate of Sponsorship", "Salary threshold", "English and role evidence"],
    routeReadiness: [
      { label: "Sponsor basis", value: "Usually required", detail: "Skilled Worker depends on a licensed sponsor and eligible occupation." },
      { label: "Profile fit", value: "Salary + code", detail: "Occupation code, salary threshold, and English ability must be checked." },
      { label: "Talent route", value: "Endorsement", detail: "Global Talent depends on endorsement or recognised evidence." },
    ],
    documentChecklist: ["Resume/CV", "Passport", "Job offer or sponsor details", "Education proof", "English evidence", "Endorsement material if applicable"],
    advisorChecks: ["Occupation code fit", "Sponsor licence readiness", "Salary threshold", "Dependent and settlement path"],
  },
  {
    slug: "australia",
    country: "Australia",
    code: "AU",
    region: "Oceania",
    image: "/images/skilled/australia/australia-186-employer-visa.webp",
    href: "/skilled/australia/employer-nomination-scheme-186",
    permitTypes: ["Employer Nomination 186", "Skilled Independent 189", "Skilled Nominated 190", "Regional 491"],
    advisoryFocus: "Skills assessment, occupation list, English score, points position, employer nomination, and regional strategy.",
    processingSignal: "Strong for points-tested professionals and employer-sponsored applicants with documented work history.",
    proofPoints: ["Skills assessment", "English score", "Occupation and points fit"],
    routeReadiness: [
      { label: "Route basis", value: "Points or employer", detail: "189/190/491 are points-led; 186/187 need employer nomination." },
      { label: "Profile fit", value: "Occupation list", detail: "Skills assessment and occupation list fit drive route viability." },
      { label: "State strategy", value: "Important", detail: "Nomination and regional options can change the best pathway." },
    ],
    documentChecklist: ["Resume/CV", "Passport", "Skills assessment material", "English score", "Employment references", "Education certificates"],
    advisorChecks: ["Occupation list fit", "Points estimate", "State/region nomination", "Employer nomination readiness"],
  },
  {
    slug: "germany",
    country: "Germany",
    code: "DE",
    region: "Europe",
    image: "/images/skilled/germany/germany-job-seeker-visa.webp",
    href: "/skilled/germany/germany-job-seeker-visa",
    permitTypes: ["Opportunity Card", "EU Blue Card", "Skilled Worker Residence", "Job seeker route"],
    advisoryFocus: "Degree recognition, salary threshold, occupation shortage, German/English profile, and job-search readiness.",
    processingSignal: "Good fit for STEM, engineering, healthcare, IT, and recognized qualification profiles.",
    proofPoints: ["Recognized qualification", "Salary or job offer", "Language and funds readiness"],
    routeReadiness: [
      { label: "Route basis", value: "Offer or points", detail: "EU Blue Card needs salary/job fit; Opportunity Card is points-based." },
      { label: "Profile fit", value: "Recognition", detail: "Degree and professional recognition are major review points." },
      { label: "Readiness", value: "Funds + language", detail: "Funds, insurance, and language evidence can affect file quality." },
    ],
    documentChecklist: ["Resume/CV", "Passport", "Degree recognition proof", "Employment letters", "Job offer if available", "Funds and insurance proof"],
    advisorChecks: ["Degree recognition", "Blue Card salary fit", "Opportunity Card score", "Consular document readiness"],
  },
  {
    slug: "uae",
    country: "UAE",
    code: "AE",
    region: "Middle East",
    image: "/images/corporate/uae/dubai-mainland-employment-visa.webp",
    href: "/corporate/uae/dubai-mainland-employment-visa",
    permitTypes: ["Mainland employment visa", "Freezone employment visa", "Investor plus employment setup", "Golden Visa talent review"],
    advisoryFocus: "Employment sponsor, freezone/mainland structure, medical/Emirates ID steps, family sponsorship, and compliance timing.",
    processingSignal: "Practical for employer-led relocation, company formation, and professional mobility into the Gulf.",
    proofPoints: ["Sponsor or company setup", "Passport and medical readiness", "Role and salary documentation"],
    routeReadiness: [
      { label: "Sponsor basis", value: "Employer/company", detail: "Mainland/freezone employment depends on sponsor or company setup." },
      { label: "Profile fit", value: "Role + salary", detail: "Role classification, salary, and company status affect process flow." },
      { label: "Family planning", value: "Structured", detail: "Family sponsorship depends on salary, tenancy, and document readiness." },
    ],
    documentChecklist: ["Resume/CV", "Passport", "Photo", "Education proof", "Employment contract or company details", "Civil documents for family"],
    advisorChecks: ["Freezone vs mainland flow", "Medical and Emirates ID sequence", "Family sponsorship", "Document attestation need"],
  },
  {
    slug: "portugal",
    country: "Portugal",
    code: "PT",
    region: "Europe",
    image: "/images/news/portugal-skilled-work-visa.webp",
    href: "/residency/portugal/portugal-d2-entrepreneur",
    permitTypes: ["Work residence direction", "D2 business route", "Highly qualified activity", "Remote/freelance route review"],
    advisoryFocus: "Employment or business basis, consular file readiness, funds, accommodation, and route timing.",
    processingSignal: "Suitable for professionals, entrepreneurs, and applicants planning European residence with a clear activity basis.",
    proofPoints: ["Work/business basis", "Funds and accommodation", "Consular documents"],
    routeReadiness: [
      { label: "Route basis", value: "Activity-led", detail: "Work, business, or highly qualified activity must be clearly supported." },
      { label: "Profile fit", value: "Consular file", detail: "Funds, accommodation, insurance, and purpose need clean documentation." },
      { label: "Timing", value: "Appointment-led", detail: "Embassy/consular timing often controls the practical calendar." },
    ],
    documentChecklist: ["Resume/CV", "Passport", "Work/business proof", "Funds proof", "Accommodation proof", "Insurance and civil documents"],
    advisorChecks: ["Route basis", "Consular file quality", "Funds and accommodation", "Family/dependent readiness"],
  },
  {
    slug: "spain",
    country: "Spain",
    code: "ES",
    region: "Europe",
    image: "/images/skilled/spain/spain-digital-nomad-visa.webp",
    href: "/skilled/spain/spain-digital-nomad-visa",
    permitTypes: ["Digital Nomad", "Highly qualified professional", "Entrepreneur route", "Corporate transfer direction"],
    advisoryFocus: "Remote income evidence, employer/client structure, social security/tax exposure, and family file readiness.",
    processingSignal: "Relevant for remote professionals, founders, and specialists with cross-border income or Spanish employer support.",
    proofPoints: ["Remote income proof", "Contracts and compliance", "Family and civil documents"],
    routeReadiness: [
      { label: "Route basis", value: "Remote/professional", detail: "Digital nomad and highly qualified routes need different evidence." },
      { label: "Profile fit", value: "Income + contracts", detail: "Income continuity, client/employer terms, and remote work basis are reviewed." },
      { label: "Compliance", value: "Tax/social security", detail: "Tax and social-security exposure should be checked before filing." },
    ],
    documentChecklist: ["Resume/CV", "Passport", "Remote work contracts", "Income proof", "Insurance", "Civil documents for family"],
    advisorChecks: ["Remote income structure", "Employer/client documentation", "Tax and social-security exposure", "Family file readiness"],
  },
  {
    slug: "italy",
    country: "Italy",
    code: "IT",
    region: "Europe",
    image: "/images/skilled/italy/italy-digital-nomad-visa.webp",
    href: "/skilled/italy/italy-digital-nomad-visa",
    permitTypes: ["Digital Nomad Visa", "Highly qualified remote work", "EU Blue Card direction"],
    advisoryFocus: "Remote income continuity, qualification evidence, accommodation, and consular file readiness for the digital nomad route.",
    processingSignal: "Relevant for experienced remote professionals and highly qualified specialists with stable non-Italian income.",
    proofPoints: ["Remote income proof", "Higher qualification or experience", "Accommodation and insurance"],
    routeReadiness: [
      { label: "Route basis", value: "Remote income", detail: "The digital nomad route reviews income level, continuity, and remote basis." },
      { label: "Profile fit", value: "Qualification", detail: "Degree or documented professional experience supports the highly qualified test." },
      { label: "Readiness", value: "Housing + cover", detail: "Accommodation and health cover are checked at consular stage." },
    ],
    documentChecklist: ["Resume/CV", "Passport", "Remote work contracts", "Income proof", "Accommodation proof", "Health insurance"],
    advisorChecks: ["Income threshold fit", "Remote work evidence", "Qualification documentation", "Consular appointment readiness"],
  },
  {
    slug: "new-zealand",
    country: "New Zealand",
    code: "NZ",
    region: "Oceania",
    image: "/images/skilled/new-zealand/green-list-work-to-residence.webp",
    href: "/skilled/new-zealand/green-list-work-to-residence-visa",
    permitTypes: ["Green List Work to Residence", "Green List Straight to Residence", "Accredited Employer Work Visa direction"],
    advisoryFocus: "Green List occupation match, employer accreditation, qualification and registration evidence, and residence sequencing.",
    processingSignal: "Strong fit for healthcare, engineering, ICT, and trades professionals on Green List occupations with employer support.",
    proofPoints: ["Green List occupation match", "Accredited employer offer", "Qualification or registration proof"],
    routeReadiness: [
      { label: "Route basis", value: "Occupation + offer", detail: "Green List routes need an eligible occupation and an accredited employer offer." },
      { label: "Profile fit", value: "Registration", detail: "Some occupations also require New Zealand professional registration." },
      { label: "Residence path", value: "Direct or 2 yrs", detail: "Tier 1 goes straight to residence; Tier 2 reaches residence after two years of work." },
    ],
    documentChecklist: ["Resume/CV", "Passport", "Job offer from accredited employer", "Qualification proof", "Registration evidence if applicable", "Health and character documents"],
    advisorChecks: ["Green List occupation fit", "Employer accreditation status", "Tier 1 vs Tier 2 sequencing", "Registration requirement check"],
  },
  {
    slug: "austria",
    country: "Austria",
    code: "AT",
    region: "Central Europe",
    image: "/images/skilled/germany/germany-immigration.webp",
    href: "/work-permits?country=austria",
    permitTypes: ["Red-White-Red Card", "EU Blue Card", "Skilled Worker in Shortage Occupation", "Red-White-Red Card plus"],
    advisoryFocus: "Points scoring, occupation on the annual shortage list, AMS labour market test, and salary evidence against the applicable collective agreement.",
    processingSignal: "Best for degree-holding professionals with a concrete Austrian job offer at senior salary levels.",
    proofPoints: ["Recognised degree or equivalent experience", "Signed Austrian job offer", "German language where the role requires it"],
    routeReadiness: [
      { label: "Sponsor basis", value: "Employer-led", detail: "Every route except the Very Highly Qualified job-seeker visa needs an Austrian employer." },
      { label: "Salary floor", value: "\u20ac55,678/yr", detail: "EU Blue Card threshold for 2026. Other Key Workers: \u20ac3,465 gross per month." },
      { label: "Family", value: "Spouse may work", detail: "Family receive a Red-White-Red Card plus, which carries unrestricted labour market access." },
    ],
    documentChecklist: ["Resume/CV", "Passport", "Degree certificates and transcripts", "Employment references", "Austrian job offer or contract", "German language certificate if the role requires it"],
    advisorChecks: ["Points score against the correct category", "Occupation on the 2026 shortage list", "Collective agreement salary check", "Family Card plus planning"],
  },
  {
    slug: "greece",
    country: "Greece",
    code: "GR",
    region: "Southern Europe",
    image: "/images/residency/greece/greece-golden-visa.webp",
    href: "/work-permits?country=greece",
    permitTypes: ["E.1 Highly Qualified (EU Blue Card)", "E.4 Dependent employment (metaklisi)", "Seasonal employment", "Tech Visa"],
    advisoryFocus: "Quota availability, employer-initiated invitation, contract length, and which of the new Law 5275/2026 categories actually fits the profile.",
    processingSignal: "Two distinct audiences: highly qualified professionals on E.1, and seasonal agriculture or tourism workers with a real Greek employer.",
    proofPoints: ["Greek employer invitation", "Degree or relevant experience for E.1", "Evidence of accommodation for seasonal routes"],
    routeReadiness: [
      { label: "Sponsor basis", value: "Employer-initiated", detail: "Only a Greek employer can start the metaklisi process. An applicant cannot self-apply." },
      { label: "Salary floor", value: "1.6\u00d7 average", detail: "EU Blue Card is set at 1.6 times the Greek average gross annual salary. Confirm the current amount with the Ministry of Migration and Asylum." },
      { label: "Quota", value: "Capped annually", detail: "Salaried and seasonal posts are limited by an annual Council of Ministers decision." },
    ],
    documentChecklist: ["Resume/CV", "Passport", "Degree certificates", "Employment references", "Greek employer invitation or contract", "Accommodation evidence for seasonal routes"],
    advisorChecks: ["Quota slot verification", "Employer registration on the ministry portal", "Correct permit category under Law 5275/2026", "Contract length and salary check"],
  },
  {
    slug: "malta",
    country: "Malta",
    code: "MT",
    region: "Southern Europe",
    image: "/images/residency/malta/malta-mprp.webp",
    href: "/work-permits?country=malta",
    permitTypes: ["Single Permit", "Key Employee Initiative (KEI)", "Specialist Employee Initiative (SEI)", "EU Blue Card"],
    advisoryFocus: "Employer eligibility under the 2025 workforce caps, vacancy advertising compliance, salary banding, and realistic family planning.",
    processingSignal: "Suits skilled professionals at an established Maltese employer that still has headroom under the third-country workforce caps.",
    proofPoints: ["Maltese employer registered with Jobsplus", "Qualification at MQF Level 6 or equivalent experience", "Salary meeting the KEI or SEI band"],
    routeReadiness: [
      { label: "Who applies", value: "Employer only", detail: "Only the Maltese employer can file, through the government single-permit portal. The applicant cannot apply." },
      { label: "Salary bands", value: "\u20ac30k / \u20ac45k", detail: "SEI from \u20ac30,000 gross a year; KEI from \u20ac45,000. Both require an ISCO Group 1\u20133 role." },
      { label: "Spouse work", value: "Not automatic", detail: "A family residence permit does not carry work rights. Dependants need their own Single Permit." },
    ],
    documentChecklist: ["Resume/CV", "Passport", "Degree certificates (MQF mapped)", "Employment references", "Maltese job offer", "Police conduct certificate"],
    advisorChecks: ["Employer headroom under the workforce caps", "Vacancy advertising compliance", "KEI versus SEI banding", "Dependant permit strategy"],
  },
  {
    slug: "cyprus",
    country: "Cyprus",
    code: "CY",
    region: "Eastern Mediterranean",
    image: "/images/residency/cyprus/cyprus-golden-visa-business-investment.webp",
    href: "/work-permits?country=cyprus",
    permitTypes: ["Companies of Foreign Interests permit", "General Employment Permit", "EU Blue Card", "Start-up visa"],
    advisoryFocus: "Whether the employer qualifies as a Company of Foreign Interests, salary banding, and whether the narrow Blue Card sectors apply.",
    processingSignal: "Strongest for skilled staff at registered foreign-interest companies. Cyprus is an EU member but not in the Schengen area.",
    proofPoints: ["Employer registered as a Company of Foreign Interests", "Degree or two years of relevant experience", "Two-year employment contract"],
    routeReadiness: [
      { label: "Sponsor basis", value: "Employer-led", detail: "The foreign-interest company route carries no cap on highly skilled hires and no labour market test." },
      { label: "Salary floor", value: "\u20ac2,500/month", detail: "Highly skilled band. A \u20ac2,000 grace rate applies only until 31 December 2026." },
      { label: "Schengen", value: "Not included", detail: "Cyprus is not a Schengen member. A Cyprus permit gives no Schengen travel right." },
    ],
    documentChecklist: ["Resume/CV", "Passport", "Degree certificates", "Two-year employment contract", "Employer foreign-interest registration", "Police conduct certificate"],
    advisorChecks: ["Foreign-interest company registration check", "Salary band and contract length", "Blue Card sector eligibility", "Family reunification planning"],
  },
  {
    slug: "bulgaria",
    country: "Bulgaria",
    code: "BG",
    region: "Southeast Europe",
    image: "/images/residency/bulgaria/bulgaria-aif.webp",
    href: "/work-permits?country=bulgaria",
    permitTypes: ["Single work and residence permit", "EU Blue Card", "Seasonal worker", "Intra-corporate transfer"],
    advisoryFocus: "Employer headcount capacity, the fifteen-day advertising requirement, and whether the Blue Card route avoids the labour market test.",
    processingSignal: "Works for genuinely employer-sponsored skilled roles, particularly IT profiles that clear the Blue Card salary floor.",
    proofPoints: ["Named Bulgarian employer", "Degree or recognised qualification", "Employer within the third-country headcount cap"],
    routeReadiness: [
      { label: "Sponsor basis", value: "Employer-led", detail: "The employer must advertise the vacancy for fifteen days. The Blue Card route is exempt from that test." },
      { label: "Salary floor", value: "1.5\u00d7 average", detail: "EU Blue Card is 1.5 times the national average gross salary. Bulgaria adopted the euro in January 2026, so older figures are stale." },
      { label: "Employer cap", value: "20% / 35%", detail: "Third-country nationals may not exceed 20% of headcount, or 35% at small and medium employers." },
    ],
    documentChecklist: ["Resume/CV", "Passport", "Degree certificates", "Employment references", "Bulgarian employment contract", "Police conduct certificate"],
    advisorChecks: ["Employer headcount capacity", "Fifteen-day advertising evidence", "Blue Card versus single permit", "Permit duration and renewal limits"],
  },
  {
    slug: "romania",
    country: "Romania",
    code: "RO",
    region: "Southeast Europe",
    image: "/images/residency/bulgaria/bulgaria-aif.webp",
    href: "/work-permits?country=romania",
    permitTypes: ["D/AM1 long-stay employment visa", "D/AM2 long-stay employment visa", "EU Blue Card"],
    advisoryFocus: "Employer registration or authorisation on the government platform, annual quota availability, and whether the role sits on the shortage occupations list.",
    processingSignal: "Romania replaced its work-permit system in April 2026. Employment permits are no longer issued; applications run through the government platform.",
    proofPoints: ["Employer registered or authorised on the state platform", "Role on the shortage occupations list for quota routes", "Bilingual employment contract"],
    routeReadiness: [
      { label: "System changed", value: "April 2026", detail: "Work permits were abolished. Any agent still selling an employment permit is selling a document that no longer exists." },
      { label: "Quota", value: "90,000 for 2026", detail: "Only the D/AM2 route consumes the quota. The 2025 quota was exhausted in early December." },
      { label: "Employer duties", value: "Substantial", detail: "Direct quota hiring requires an authorised employer with trading history, headcount and a financial guarantee per worker." },
    ],
    documentChecklist: ["Resume/CV", "Passport", "Qualification certificates", "Employment references", "Bilingual Romanian employment contract", "Police conduct certificate"],
    advisorChecks: ["Employer status on the government platform", "Quota availability for the year", "Shortage occupation code match", "Contract and language compliance"],
  },
];

export function findWorkPermitCountry(slugOrCountry: string | undefined) {
  if (!slugOrCountry) return undefined;
  const value = slugOrCountry.toLowerCase().trim();
  return workPermitCountries.find(
    (item) => item.slug === value || item.country.toLowerCase() === value,
  );
}
