// src/lib/eligibility/programCatalog.ts
// Enriched, non-breaking catalog for use in suggestions and PDFs.
// NOTE: Thresholds/timelines vary by case and change often; treat as indicative.
// Keep `name` stable since other components may rely on it.

export const Programs = {
  residency: [
    {
      slug: "pt-alt-routes",
      name: "Portugal (Alt. routes)",
      country: "Portugal",
      pathway: "Residency by investment (funds/donation/arts/VC) or professional routes",
      minInvestmentUSD: "≈ 200k–500k+ (route dependent)",
      processingTime: "6–12 months (typical)",
      familyIncluded: true,
      requiresPhysicalPresence: "Low–Moderate (maintain ties; specifics vary by route)",
      notes:
        "Property route rules changed; alternative compliant options exist (funds, cultural, R&D). Residency can lead to citizenship subject to residence and language.",
    },
    {
      slug: "gr-property",
      name: "Greece Property Route",
      country: "Greece",
      pathway: "Residency by real estate investment",
      minInvestmentUSD: "≈ 250k–800k+ (region dependent)",
      processingTime: "3–6 months (typical after purchase)",
      familyIncluded: true,
      requiresPhysicalPresence: "Minimal (renewal conditions apply)",
      notes:
        "Threshold depends on municipality/region. Allows spouse and dependent children; long-term path to citizenship with residence & language.",
    },
    {
      slug: "uae-residency",
      name: "UAE Residency",
      country: "United Arab Emirates",
      pathway: "Employment, company setup, investor/real-estate, freelancer & remote worker routes",
      minInvestmentUSD: "Varies by route (company setup/real estate/fees)",
      processingTime: "1–8 weeks (route dependent)",
      familyIncluded: true,
      requiresPhysicalPresence: "Low (entry/medical/ID issuance required)",
      notes:
        "Multiple pathways with fast processing. Golden Visa available for qualifying investors/talents with longer validity.",
    },
    {
      slug: "us-eb5-investor",
      name: "USA EB-5 Investor Immigrant Visa",
      country: "United States",
      pathway: "Green Card through qualifying investment and job creation",
      minInvestmentUSD: "USD 800k+ TEA / USD 1.05M+ standard + fees",
      processingTime: "18-48+ months (petition and visa availability dependent)",
      familyIncluded: true,
      requiresPhysicalPresence: "Settlement in the United States after immigrant visa/adjustment",
      notes:
        "Investor route for applicants who can document lawful funds and job-creation compliance. Source-of-funds and project due diligence are critical.",
    },
    {
      slug: "ca-start-up-visa",
      name: "Canada Start-Up Visa",
      country: "Canada",
      pathway: "Permanent residence for founders with designated organization support",
      minInvestmentUSD: "No fixed government investment; settlement funds and business costs apply",
      processingTime: "24-40+ months (work permit may be possible earlier)",
      familyIncluded: true,
      requiresPhysicalPresence: "Settlement in Canada after PR; business activity expected",
      notes:
        "Best for scalable founders who can secure incubator, angel, or venture support. Business viability and founder role require advisor review.",
    },
    {
      slug: "uk-innovator-founder",
      name: "UK Innovator Founder Visa",
      country: "United Kingdom",
      pathway: "Founder route for innovative, viable, and scalable business ideas",
      minInvestmentUSD: "No fixed minimum investment; business funding must be credible",
      processingTime: "3-8 weeks after endorsement and application readiness",
      familyIncluded: true,
      requiresPhysicalPresence: "High - founder is expected to run the business in the UK",
      notes:
        "Requires endorsement by an approved body and a strong business case. Can lead to settlement if growth milestones are met.",
    },
    {
      slug: "nz-active-investor-plus",
      name: "New Zealand Active Investor Plus",
      country: "New Zealand",
      pathway: "Investor residence through acceptable active investments",
      minInvestmentUSD: "Typically high-capital route; investment weighting varies",
      processingTime: "6-18+ months after investment strategy and evidence",
      familyIncluded: true,
      requiresPhysicalPresence: "Moderate - residence and investment conditions apply",
      notes:
        "Premium investor pathway where investment type, holding period, and source-of-funds evidence are central to eligibility.",
    },
    {
      slug: "sg-global-investor-programme",
      name: "Singapore Global Investor Programme",
      country: "Singapore",
      pathway: "Permanent residence for established entrepreneurs and investors",
      minInvestmentUSD: "High-capital route; qualifying investment options apply",
      processingTime: "9-18+ months (case dependent)",
      familyIncluded: true,
      requiresPhysicalPresence: "Moderate to high - business and residence commitments apply",
      notes:
        "For experienced business owners or investors with strong track records. Net worth, turnover, investment plan, and family structure need review.",
    },
    {
      slug: "es-digital-nomad",
      name: "Spain Digital Nomad Residence",
      country: "Spain",
      pathway: "Residence for remote workers and qualifying digital professionals",
      minInvestmentUSD: "No investment route; income and remote-work evidence required",
      processingTime: "1-4 months after document readiness",
      familyIncluded: true,
      requiresPhysicalPresence: "Moderate - residence and tax planning should be reviewed",
      notes:
        "Useful for remote professionals and founders serving non-Spanish clients. Income, employment status, social security, and tax exposure require review.",
    },
    {
      slug: "sa-premium-residency",
      name: "Saudi Premium Residency",
      country: "Saudi Arabia",
      pathway: "Premium residency for investors, entrepreneurs, talents, and eligible categories",
      minInvestmentUSD: "Route dependent; government fees and category thresholds apply",
      processingTime: "1-4 months after evidence readiness",
      familyIncluded: true,
      requiresPhysicalPresence: "Variable - category and renewal conditions apply",
      notes:
        "Emerging GCC residency option for business owners, investors, executives, and special talents. Category fit should be checked carefully.",
    },
  ],

  citizenship: [
    {
      slug: "it-jure-sanguinis",
      name: "Italy by Descent",
      country: "Italy",
      pathway: "Citizenship jure sanguinis (by descent)",
      minInvestmentUSD: "N/A",
      processingTime: "6–24+ months (municipality/consulate dependent)",
      familyIncluded: "Lineal descendants may benefit",
      requiresPhysicalPresence: "Varies (municipal processing/residency cases differ)",
      notes:
        "Eligibility depends on uninterrupted lineage and dates (no renunciation in the line). Documentation and legalization required.",
    },
    {
      slug: "ie-foreign-birth-register",
      name: "Ireland by Descent",
      country: "Ireland",
      pathway: "Citizenship by descent (Foreign Births Register)",
      minInvestmentUSD: "N/A",
      processingTime: "6–18+ months (batch dependent)",
      familyIncluded: "Passes to next generation once you’re registered (rules apply)",
      requiresPhysicalPresence: "No ongoing residence needed",
      notes:
        "Generally available if a parent/grandparent was an Irish citizen at your birth (documentation and FBR registration required).",
    },
    {
      slug: "caribbean-cbi",
      name: "Caribbean CBI",
      country: "Caribbean (program-dependent)",
      pathway: "Citizenship by investment (donation or real estate)",
      minInvestmentUSD: "≈ 200k+ (program/option dependent) + fees",
      processingTime: "3–8 months (enhanced due diligence)",
      familyIncluded: true,
      requiresPhysicalPresence: "Usually none",
      notes:
        "Program terms and minimums change periodically; strict due diligence applies. Choose by visa access, family add-ons, and timelines.",
    },
    {
      slug: "mt-exceptional-services",
      name: "Malta (Exceptional Services)",
      country: "Malta",
      pathway: "Citizenship for exceptional services by direct investment",
      minInvestmentUSD: "≈ 600k–750k+ contribution + property & donation",
      processingTime: "12–36 months (eligibility periods apply)",
      familyIncluded: true,
      requiresPhysicalPresence: "Residence period before eligibility",
      notes:
        "Structured multi-part contribution with mandatory residence period; rigorous due diligence and compliance requirements.",
    },
    {
      slug: "tr-cbi",
      name: "Turkey Citizenship by Investment",
      country: "Turkey",
      pathway: "Citizenship through qualifying real estate, deposit, or investment options",
      minInvestmentUSD: "USD 400k+ real estate route; other options vary",
      processingTime: "4-9 months (case and government timing dependent)",
      familyIncluded: true,
      requiresPhysicalPresence: "Usually low; biometric/document steps apply",
      notes:
        "Popular citizenship-by-investment route with real-estate and financial options. Property title, valuation, sanctions, and source-of-funds checks matter.",
    },
    {
      slug: "eg-cbi",
      name: "Egypt Citizenship by Investment",
      country: "Egypt",
      pathway: "Citizenship through donation, real estate, bank deposit, or business investment",
      minInvestmentUSD: "Route dependent; donation/deposit/real-estate options apply",
      processingTime: "6-12+ months (government and due diligence dependent)",
      familyIncluded: true,
      requiresPhysicalPresence: "Low to moderate; document and government steps apply",
      notes:
        "Useful for applicants seeking a non-Caribbean CBI option. Route selection, family inclusion, and due diligence must be verified.",
    },
    {
      slug: "vu-cbi",
      name: "Vanuatu Citizenship by Investment",
      country: "Vanuatu",
      pathway: "Citizenship through approved contribution route",
      minInvestmentUSD: "USD 130k+ indicative donation route plus fees",
      processingTime: "2-4 months (case dependent)",
      familyIncluded: true,
      requiresPhysicalPresence: "Usually none",
      notes:
        "Fast citizenship route with strict compliance review. Passport mobility, bank acceptance, and programme changes require advisor confirmation.",
    },
    {
      slug: "ag-cbi",
      name: "Antigua and Barbuda Citizenship by Investment",
      country: "Antigua and Barbuda",
      pathway: "Citizenship through contribution, real estate, or business options",
      minInvestmentUSD: "USD 230k+ indicative contribution plus fees",
      processingTime: "4-8 months (due diligence dependent)",
      familyIncluded: true,
      requiresPhysicalPresence: "Low; short stay requirement may apply",
      notes:
        "Family-friendly Caribbean CBI option. Fees, family composition, due diligence, and travel-access priorities should drive selection.",
    },
    {
      slug: "dm-cbi",
      name: "Dominica Citizenship by Investment",
      country: "Dominica",
      pathway: "Citizenship through contribution or approved real estate",
      minInvestmentUSD: "USD 200k+ indicative route plus fees",
      processingTime: "4-8 months (due diligence dependent)",
      familyIncluded: true,
      requiresPhysicalPresence: "Usually none",
      notes:
        "Established Caribbean CBI route. Applicant background, source of funds, dependents, and programme updates require advisor review.",
    },
    {
      slug: "gd-cbi",
      name: "Grenada Citizenship by Investment",
      country: "Grenada",
      pathway: "Citizenship through contribution or approved real estate",
      minInvestmentUSD: "USD 235k+ indicative contribution plus fees",
      processingTime: "4-8 months (due diligence dependent)",
      familyIncluded: true,
      requiresPhysicalPresence: "Usually none",
      notes:
        "Known for mobility planning and treaty considerations. Due diligence, dependent eligibility, and route purpose must be reviewed.",
    },
  ],

  corporate: [
    {
      slug: "ict-transfer",
      name: "Intra-Company Transfer",
      country: "Various (e.g., UK/EU, Canada, UAE, Singapore)",
      pathway: "Employer-sponsored transfer of key staff",
      minInvestmentUSD: "N/A (employer costs/fees apply)",
      processingTime: "2–12+ weeks (jurisdiction dependent)",
      familyIncluded: true,
      requiresPhysicalPresence: "Yes (work location)",
      notes:
        "Ideal for relocating managers/specialists within multinational groups; often requires qualifying relationship and salary thresholds.",
    },
    {
      slug: "entity-plus-visa",
      name: "Entity + Employer Visa",
      country: "Various",
      pathway: "Incorporation plus employer sponsorship privileges",
      minInvestmentUSD: "Setup & capitalization vary by jurisdiction",
      processingTime: "2–8 weeks for setup + visa timelines",
      familyIncluded: true,
      requiresPhysicalPresence: "Yes (sponsored employees on site)",
      notes:
        "Combine company formation with sponsor licence/establishment card to hire or relocate talent. Good for building a local presence.",
    },
    {
      slug: "uae-golden-visa",
      name: "UAE Golden Visa",
      country: "United Arab Emirates",
      pathway: "Long-term residence for investors/talents",
      minInvestmentUSD: "Real estate ≈ AED 2M+ (or other qualifying routes)",
      processingTime: "2–6 weeks (route dependent)",
      familyIncluded: true,
      requiresPhysicalPresence: "Low (entry/medical/ID issuance required)",
      notes:
        "10-year residence for qualifying investors and talents; flexible renewals and family sponsorship benefits.",
    },
    {
      slug: "us-l1",
      name: "USA L-1 Intra-Company Transfer",
      country: "United States",
      pathway: "Transfer executive, manager, or specialized knowledge employee to a US entity",
      minInvestmentUSD: "N/A; company setup, payroll, and legal costs apply",
      processingTime: "1-6 months depending on petition strategy",
      familyIncluded: true,
      requiresPhysicalPresence: "High - work must be performed for the US entity",
      notes:
        "Strong for companies expanding to the United States. Requires qualifying foreign employment, related entities, role evidence, and business operations.",
    },
    {
      slug: "us-e2-treaty-investor",
      name: "USA E-2 Treaty Investor Visa",
      country: "United States",
      pathway: "Treaty investor visa for substantial investment in a US business",
      minInvestmentUSD: "No fixed minimum; investment must be substantial and active",
      processingTime: "2-6 months depending on consulate and business readiness",
      familyIncluded: true,
      requiresPhysicalPresence: "High - investor directs and develops the business",
      notes:
        "Available only to eligible treaty nationals. Business plan, ownership, investment at risk, and applicant nationality require review.",
    },
    {
      slug: "us-h1b",
      name: "USA H-1B Specialty Occupation",
      country: "United States",
      pathway: "Employer-sponsored specialty occupation work visa",
      minInvestmentUSD: "N/A; employer sponsorship and filing costs apply",
      processingTime: "Lottery/cap timing or cap-exempt timing varies",
      familyIncluded: true,
      requiresPhysicalPresence: "High - US employment required",
      notes:
        "Best for degree-aligned professional roles with a sponsoring employer. Cap, wage, specialty occupation, and employer compliance are key.",
    },
    {
      slug: "uk-sponsor-skilled-worker",
      name: "UK Sponsor Licence + Skilled Worker",
      country: "United Kingdom",
      pathway: "Employer sponsorship through licensed UK sponsor",
      minInvestmentUSD: "N/A; sponsor licence and employment costs apply",
      processingTime: "4-12+ weeks for licence and visa readiness",
      familyIncluded: true,
      requiresPhysicalPresence: "High - UK job role required",
      notes:
        "For companies hiring or relocating talent into the UK. Sponsor compliance, salary, occupation code, and genuine vacancy must be managed.",
    },
    {
      slug: "sg-employment-pass",
      name: "Singapore Employment Pass",
      country: "Singapore",
      pathway: "Work pass for managers, executives, and specialists",
      minInvestmentUSD: "N/A; salary and employer costs apply",
      processingTime: "3-8 weeks after employer readiness",
      familyIncluded: true,
      requiresPhysicalPresence: "High - Singapore employment required",
      notes:
        "Employer-led route for professionals. Salary, COMPASS-style profile, employer standing, and dependent eligibility require review.",
    },
    {
      slug: "ca-global-talent-stream",
      name: "Canada Global Talent Stream",
      country: "Canada",
      pathway: "Fast work permit route for high-demand technology and specialist roles",
      minInvestmentUSD: "N/A; employer labour-market and compliance costs apply",
      processingTime: "2-8+ weeks after employer documents are ready",
      familyIncluded: true,
      requiresPhysicalPresence: "High - Canadian employment required",
      notes:
        "Useful for tech and specialist hiring. Employer eligibility, wages, Labour Market Benefits Plan, and occupation fit must be checked.",
    },
  ],

  skilled: [
    {
      slug: "ca-express-entry",
      name: "Canada Express Entry",
      country: "Canada",
      pathway: "Points-based permanent residence (CRS)",
      minInvestmentUSD: "N/A",
      processingTime: "6–12 months after ITA (varies)",
      familyIncluded: true,
      requiresPhysicalPresence: "Settlement after landing (PR obligations apply)",
      notes:
        "CRS scores depend on age, education, language, experience; PNP nominations can boost scores. IELTS/CELPIP and ECA required.",
    },
    {
      slug: "au-skilled-189-190",
      name: "Australia Skilled (189/190)",
      country: "Australia",
      pathway: "Points-based skilled migration (independent or state nominated)",
      minInvestmentUSD: "N/A",
      processingTime: "Varies by round/state and occupation",
      familyIncluded: true,
      requiresPhysicalPresence: "Settlement in Australia (state commitments may apply)",
      notes:
        "Points from age, English, education, occupation; state nomination (190) increases competitiveness. Skills assessment required.",
    },
    {
      slug: "pnps-state-nominee",
      name: "Provincial/State Nominee",
      country: "Canada/Australia (regional programs)",
      pathway: "Nomination by province/state for in-demand occupations",
      minInvestmentUSD: "N/A",
      processingTime: "Varies by stream",
      familyIncluded: true,
      requiresPhysicalPresence: "Settlement in nominating region (conditions apply)",
      notes:
        "Useful when federal points are borderline. Prior ties, job offers, or study history can help eligibility.",
    },
    {
      slug: "us-eb1a",
      name: "USA EB-1A Extraordinary Ability",
      country: "United States",
      pathway: "Immigrant visa/Green Card for sustained national or international acclaim",
      minInvestmentUSD: "N/A",
      processingTime: "8-24+ months depending on strategy and visa availability",
      familyIncluded: true,
      requiresPhysicalPresence: "Settlement in the United States after approval/availability",
      notes:
        "For top-tier professionals, founders, researchers, artists, executives, and athletes. Awards, media, publications, judging, salary, and original contribution evidence matter.",
    },
    {
      slug: "us-eb2-niw",
      name: "USA EB-2 National Interest Waiver",
      country: "United States",
      pathway: "Immigrant visa/Green Card for advanced degree or exceptional ability with national-interest case",
      minInvestmentUSD: "N/A",
      processingTime: "10-30+ months depending on petition and visa availability",
      familyIncluded: true,
      requiresPhysicalPresence: "Settlement in the United States after approval/availability",
      notes:
        "Good for founders, researchers, technologists, healthcare and high-impact professionals. Evidence must show merit, applicant positioning, and national benefit.",
    },
    {
      slug: "us-o1",
      name: "USA O-1 Extraordinary Ability Visa",
      country: "United States",
      pathway: "Temporary work visa for extraordinary ability in sciences, business, arts, education, or athletics",
      minInvestmentUSD: "N/A; sponsor/agent and filing costs apply",
      processingTime: "1-4 months depending on evidence and premium processing",
      familyIncluded: true,
      requiresPhysicalPresence: "High - US work/events required",
      notes:
        "Useful for high-achieving professionals before or alongside permanent residence strategy. Evidence quality and sponsor structure are critical.",
    },
    {
      slug: "us-f1-opt",
      name: "USA F-1 Student to OPT/STEM OPT",
      country: "United States",
      pathway: "Study route with post-completion practical training options",
      minInvestmentUSD: "Tuition and living funds required",
      processingTime: "University admission plus visa timing; OPT follows programme completion",
      familyIncluded: true,
      requiresPhysicalPresence: "High - full-time study in the United States",
      notes:
        "Education-first pathway for students and career switchers. School choice, funding, study intent, and post-study strategy need planning.",
    },
    {
      slug: "us-j1-research",
      name: "USA J-1 Research / Exchange Visitor",
      country: "United States",
      pathway: "Exchange visitor route for research, training, teaching, or specialist programmes",
      minInvestmentUSD: "N/A; sponsor/programme funding varies",
      processingTime: "1-4 months after sponsor documents",
      familyIncluded: true,
      requiresPhysicalPresence: "High - programme participation in the United States",
      notes:
        "Useful for researchers, scholars, trainees, and exchange participants. Two-year home residency rules may apply and must be checked.",
    },
    {
      slug: "uk-global-talent",
      name: "UK Global Talent Visa",
      country: "United Kingdom",
      pathway: "Talent route for leaders or potential leaders in academia, research, arts, culture, or digital technology",
      minInvestmentUSD: "N/A",
      processingTime: "3-10 weeks depending on endorsement path",
      familyIncluded: true,
      requiresPhysicalPresence: "High if building UK career; settlement route available",
      notes:
        "Strong for researchers, tech leaders, creators, and award winners. Endorsement evidence and field-specific criteria drive success.",
    },
    {
      slug: "de-eu-blue-card",
      name: "Germany EU Blue Card",
      country: "Germany",
      pathway: "Skilled work residence for qualified professionals with qualifying salary/job",
      minInvestmentUSD: "N/A",
      processingTime: "1-4 months after job and documents are ready",
      familyIncluded: true,
      requiresPhysicalPresence: "High - German employment required",
      notes:
        "For degree-qualified professionals with a German job offer. Salary threshold, degree recognition, and occupation fit require review.",
    },
    {
      slug: "au-global-talent-858",
      name: "Australia National Innovation / Global Talent",
      country: "Australia",
      pathway: "Permanent visa for exceptional talent in target sectors",
      minInvestmentUSD: "N/A",
      processingTime: "6-18+ months depending on invitation and evidence",
      familyIncluded: true,
      requiresPhysicalPresence: "Settlement in Australia after grant",
      notes:
        "For exceptional professionals in future-focused sectors. Achievements, salary, nomination, and sector fit require advisor review.",
    },
    {
      slug: "nz-skilled-migrant",
      name: "New Zealand Skilled Migrant Category",
      country: "New Zealand",
      pathway: "Residence for skilled workers with qualifying job and points evidence",
      minInvestmentUSD: "N/A",
      processingTime: "6-18+ months after job and evidence readiness",
      familyIncluded: true,
      requiresPhysicalPresence: "High - skilled employment and settlement expected",
      notes:
        "For applicants with skilled New Zealand employment. Points, qualification recognition, salary, and family documentation matter.",
    },
    {
      slug: "jp-highly-skilled-professional",
      name: "Japan Highly Skilled Professional",
      country: "Japan",
      pathway: "Points-based residence for advanced academic, specialist, or business management professionals",
      minInvestmentUSD: "N/A for employment routes; business management costs may apply",
      processingTime: "1-4 months after employer/business evidence",
      familyIncluded: true,
      requiresPhysicalPresence: "High - Japan activity required",
      notes:
        "For high-scoring professionals and executives. Education, income, experience, age, Japanese language and employer/business context affect score.",
    },
  ],
} as const;
